version: '3'
services:
  ktp:
    build: .
    ports: 
      - 8085:8080
    networks:
      - dbconnect
    depends_on:
      - "mariadb"
    restart: unless-stopped
  mariadb:
    image: mariadb:10.3
    ports:
      - 3311:3306
    environment:
      - MYSQL_ROOT_PASSWORD=reihan
      - MYSQL_DATABASE=ktp
      - MYSQL_USER=reihan
      - MYSQL_PASSWORD=reihan
    networks:
      - dbconnect
    restart: unless-stopped
networks:
  dbconnect:
    driver: bridge