version: '3'
services:
  ktp:
    build: .
    ports: 
      - 8080:8080
    networks:
      - dbconnect
    depends_on:
      - "mariadb"
    restart: unless-stopped
  mariadb:
    image: mariadb:10.3
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - dbconnect
    volumes:
      - maria-data:/var/lib/mysql/data
    restart: unless-stopped
networks:
  dbconnect:
    driver: bridge
volumes:
  maria-data:
    driver: local
